### ISSUE TITLE
GUID conflicts on 2020.3..22f1c1, newtonsoft version 13.0.1

### ISSUE THREAD

**Issue by orangeagain** [jilleJr/Newtonsoft.Json-for-Unity#139] opened 2021-11-15 13:26 UTC
Use auto installer unity package to install. and show errors every time:

```
GUID [6c694cfdc33ae264fb33e0cd1c7e25cf] for asset 'Packages/jillejr.newtonsoft.json-for-unity/Plugins/Newtonsoft.Json AOT/Newtonsoft.Json.dll' conflicts with:
  'Packages/com.unity.nuget.newtonsoft-json/Runtime/AOT/Newtonsoft.Json.dll' (current owner)
We can't assign a new GUID because the asset is in an immutable folder. The asset will be ignored.

GUID [8c4bfcb5b17948478ccb955bccff9652] for asset 'Packages/jillejr.newtonsoft.json-for-unity/Plugins/Newtonsoft.Json Editor/Newtonsoft.Json.dll' conflicts with:
  'Packages/com.unity.nuget.newtonsoft-json/Runtime/Newtonsoft.Json.dll' (current owner)
We can't assign a new GUID because the asset is in an immutable folder. The asset will be ignored.

```

**Comment by orangeagain** [comment] 2021-11-15 16:55
after import `jillejr.newtonsoft.json-for-unity@13.0.102` and `com.unity.nuget.newtonsoft-json@2.0.0` both exist in PackageCache floder sametime, maybe that is problem

**Comment by orangeagain** [comment] 2021-11-15 17:08
**I found the reason.**
The unity `version control` package include a newtonsoft. when I remove `version control` in packagemanager, the error disappear!

**Comment by jilleJr** [comment] 2021-11-15 21:39
Hello @orangeagain! Thank you for submitting this!

Sorry that you have to deal with this, but as you've noticed there's an incompatibility between this package and Unity's.

As of today, you can only use either my package or Unity's. But not both.

The issue itself is caused by the GUID collisions of the .meta files. I could regenerate all the GUIDs in my package, but that could break existing uses where users rely on the GUIDs inside this package, and there would still be the issue with the duplicate Newtonsoft.Json.dll files and duplicate Newtonsoft.Json namespaces being loaded.

**Comment by jilleJr** [comment] 2021-11-15 22:06
I'm closing this as "resolved". Please reopen if I misunderstood, and don't fray in opening new issues if you encounter anything else!

**Closed by jilleJr** 2021-11-15 22:06 UTC
Labels: bug
